# Generated by Django 5.1.1 on 2024-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=270)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_produk/')),
                ('ukuran', models.CharField(blank=True, max_length=20, null=True)),
                ('warna', models.CharField(blank=True, max_length=50, null=True)),
                ('diskon', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
